### ISSUE TITLE
Add an ability to select the order state for successful payments

### ISSUE THREAD

**Issue by villesiltala** [CheckoutFinland/checkout-finland-for-woocommerce#20]
The default state of an order after a successful order is "processing". This is problematic for WooCommerce shops that do not require any kind of processing for the order after the payment is completed. For example, shops with digital downloads might not need any processing on behalf of the shop administrator. In this case, the order should be "completed" after the payment.

This feature could be done with a select box on the payment gateway settings page.

**Comment by TeemuSuoranta** [comment]
I had the same issue with a donation based WooCommerce store and solved it by making product type "virtual/downloadable" without any files. The state "processing" for physical products and services is a built-in feature for WooCommerce as far as I know.

**Comment by eerohakio** [comment]
This functionality is based on Woocommerce see from https://docs.woocommerce.com/document/managing-orders/.
As per Woocommerce these scenarios apply:
- Cart includes only virtual&downloadable products -> Order is in "Completed" state when payment completed
- Cart includes something else than only virtual&downloadable products -> Order is in "Processing" state when payment completed

There is already plugin in Woocommerce store that has ability to change order state when creating orders https://woocommerce.com/products/woocommerce-order-status-control/
