### ISSUE TITLE
Checkout.fi payment option not visible in WooCommerce Payment options

### ISSUE THREAD

**Issue by lopaavol** [CheckoutFinland/checkout-finland-for-woocommerce#8]
I installed and activated the plugin but it is not showing up in WooCommerce Payment methods. The installation and activation worked without errors. My current setup is:
PHP: 7.2.19
WordPress: 5.2.1
WooCommerce: 3.6.4
CheckoutFinland plugin: 1.1.3

**Comment by airfishX** [comment]
Same problem
Running PHP version: 7.1.30
WordPress 5.2.1
WooCommerce: 3.6.4
CheckoutFinland plugin: 1.1.3

**Comment by villesiltala** [comment]
@lopaavol, @airfishX, did you install the plugin with composer or manually?

The manual installation guide has not been updated since the initial release and is missing a vital part. If the installation is done manually, you must run `composer install` inside the plugin directory in order for the plugin to work. That will install the required php-sdk package and the autoloader for the plugin.

This gateway plugin is going to be released in WordPress Plugins eventually and that plugin version will contain the required packages.

**Comment by dahrari** [comment]
You then might want to advise Checkout people to take the manual installation guide away from their site if it's a totally deprecated installation route.

**Comment by Gauranga-Nityananda** [comment]
@villesiltala , Can you kindly help out how to install this plugin using composer? I'm new in coding.

**Comment by mstadius** [comment]
I am having the same problem. I installed using composer and activated the plugin but it is not listed in the payment methods list in WooCommerce settings. Do you have any suggestions what to do?

Wordpress: 5.2.4
WooCommerce: 3.7.1
PHP: 7.3.9

Here is the output of composer when i installed:

```sh
php composer.phar require checkoutfinland/woocommerce-checkout-finland-gateway
Using version ^1.1 for checkoutfinland/woocommerce-checkout-finland-gateway
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 10 installs, 0 updates, 0 removals
  - Installing composer/installers (v1.7.0): Downloading (100%)         
  - Installing symfony/polyfill-mbstring (v1.12.0): Downloading (100%)         
  - Installing respect/validation (1.1.31): Downloading (100%)         
  - Installing guzzlehttp/promises (v1.3.1): Downloading (100%)         
  - Installing ralouphie/getallheaders (3.0.3): Downloading (100%)         
  - Installing psr/http-message (1.0.1): Downloading (100%)         
  - Installing guzzlehttp/psr7 (1.6.1): Downloading (100%)         
  - Installing guzzlehttp/guzzle (6.3.3): Downloading (100%)         
  - Installing checkoutfinland/sdk (1.0.0): Downloading (100%)         
  - Installing checkoutfinland/woocommerce-checkout-finland-gateway (1.1.7): Downloading (100%)
```

**Comment by loueranta** [comment]
Thanks for letting us know, we will look in to this.

We are preparing the plugin to be released on Wordpress.org, so that installing and updating will be easier in the future.

**Comment by traone** [comment]
You can find the [latest](https://github.com/OPMerchantServices/op-payment-service-for-woocommerce/releases/download/1.1.7/1.1.7.zip) ready to install zip-archive under Code > Releases.  

Installing this package works out of the box.

On the next upcoming release, we will instruct this a bit better in the README file.

Also in the near future, we will be releasing this plugin in the Wordpress Plugins repository.

**Comment by loueranta** [comment]
@lopaavol / @airfishX / @dahrari / @Gauranga-Nityananda / @mstadius : The plugin is now available at WordPress.org Plugin Directory: [OP Payment Service for WooCommerce](https://wordpress.org/plugins/op-payment-service-for-woocommerce/)

You can install it directly from WordPress Admin panel. Go to "Plugins" -> "Add New" and type "OP Payment Service for WooCommerce" in to the search box to find the plugin. 

If this doesn't solve your installation problems, please open a new issue.
