### ISSUE TITLE
Guzzlehttp/guzzle version conflicts with other plugins

### ISSUE THREAD

**Issue by ThistleFIN** [CheckoutFinland/checkout-finland-for-woocommerce#89]
**Describe the bug**
Guzzlehttp/guzzle is on version 6.x.x wich conflicts with other plugin that have a newer version of Guzzlehttp/guzzle 7.3.0 causing fatal error.

**To Reproduce**
Any plugin with a newer version of Guzzle, for example plugins using google/apiclient v2.10.1 sometimes cause fatal error with Checkout -plugin.

**Error Code**
`Uncaught Error: Call to undefined method GuzzleHttp\Utils::chooseHandler() in /srv/asteriski.fi/wp-content/plugins/wp-asteriski-calendar/vendor/guzzlehttp/guzzle/src/functions.php:61 Stack trace: #0 /srv/asteriski.fi/wp-content/plugins/op-payment-service-for-woocommerce/vendor/guzzlehttp/guzzle/src/HandlerStack.php(42): GuzzleHttp\choose_handler() #1 /srv/asteriski.fi/wp-content/plugins/op-payment-service-for-woocommerce/vendor/guzzlehttp/guzzle/src/Client.php(65): GuzzleHttp\HandlerStack::create() #2 /srv/asteriski.fi/wp-content/plugins/wp-asteriski-calendar/vendor/google/apiclient/src/Client.php(1190): GuzzleHttp\Client->__construct() #3 /srv/asteriski.fi/wp-content/plugins/wp-asteriski-calendar/vendor/google/apiclient/src/Client.php(1143): Google\Client->createDefaultHttpClient() #4 /srv/asteriski.fi/wp-content/plugins/wp-asteriski-calendar/vendor/google/apiclient/src/Client.php(411): Google\Client->getHttpClient() #5 /srv/asteriski.fi/wp-content/plugins/wp-asteriski-calendar/vendor/google/apiclient/src/Client.php(891): Google\Client->authorize() #6 /srv/asteriski.fi/wp-content/plugins/wp-asteriski-calendar/vendor/google/apiclient/src/Service/Resource.php(238): Google\Client->execute() #7 /srv/asteriski.fi/wp-content/plugins/wp-asteriski-calendar/vendor/google/apiclient-services/src/Calendar/Resource/Events.php(271): Google\Service\Resource->call() #8 /srv/asteriski.fi/wp-content/plugins/wp-asteriski-calendar/wp-asteriski-calendar.php(94): Google\Service\Calendar\Resource\Events->listEvents() #9 /srv/asteriski.fi/wp-includes/class-wp-widget.php(393): Next_Events->widget() #10 /srv/asteriski.fi/wp-includes/widgets.php(831): WP_Widget->display_callback() #11 /srv/asteriski.fi/wp-content/themes/wp-asteriski-theme/sidebar.php(6): dynamic_sidebar() #12 /srv/asteriski.fi/wp-includes/template.php(770): require_once('...') #13 /srv/asteriski.fi/wp-includes/template.php(716): load_template() #14 /srv/asteriski.fi/wp-includes/general-template.php(136): locate_template() #15 /srv/asteriski.fi/wp-content/themes/wp-asteriski-theme/index.php(136): get_sidebar() #16 /srv/asteriski.fi/wp-includes/template-loader.php(106): include('...') #17 /srv/asteriski.fi/wp-blog-header.php(19): require_once('...') #18 /srv/asteriski.fi/index.php(17): require('...') #19 {main} thrown in /srv/asteriski.fi/wp-content/plugins/wp-asteriski-calendar/vendor/guzzlehttp/guzzle/src/functions.php on line 61`

**Comment by loueranta** [comment]
@ThistleFIN We have now fixed this Guzzle  #issue by removing the dependency from the plugin (#91)
Please update to the latest version (1.7+)
