### ISSUE TITLE
Cannot get plugin to work

### ISSUE THREAD

**Issue by maavalko** [CheckoutFinland/checkout-finland-for-woocommerce#9]
When user tries to pay, result is only error.

Wordpress 5.5.2
WooCommerce 3.7.0
Plugin 1.1.3

Server logs show following error.

AH01071: Got error 'PHP message: PHP Warning: Division by zero in /var/www/vhosts/mavacom.fi/cross4wd.mavacom.fi/wp-content/plugins/woocommerce-checkout-finland-gateway/src/Gateway.php on line 1133\nPHP message: PHP Fatal error: Uncaught Error: Call to a member function getName() on null in /var/www/vhosts/mavacom.fi/cross4wd.mavacom.fi/wp-content/plugins/woocommerce-checkout-finland-gateway/src/Gateway.php:712\nStack trace:\n#0 /var/www/vhosts/mavacom.fi/cross4wd.mavacom.fi/wp-content/plugins/woocommerce/includes/class-wc-checkout.php(924): CheckoutFinland\\WooCommercePaymentGateway\\Gateway->process_payment(2691)\n#1 /var/www/vhosts/mavacom.fi/cross4wd.mavacom.fi/wp-content/plugins/woocommerce/includes/class-wc-checkout.php(1124): WC_Checkout->process_order_payment(2691, 'checkout_finlan...')\n#2 /var/www/vhosts/mavacom.fi/cross4wd.mavacom.fi/wp-content/plugins/woocommerce/includes/class-wc-ajax.php(462): WC_Checkout->process_checkout()\n#3 /var/www/vhosts/mavacom.fi/cross4wd.mavacom.fi/wp-includes/class-wp-hook.php(286): WC_AJAX::checkout('')\n#4 /var/www/vhosts/mavacom.fi/cross4wd.mavacom.fi/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters('', Array)\n#5 /var/www/vhosts/mavacom.fi/cross4wd.mava...\n', referer: https://cross4wd.mavacom.fi/kassa/

**Comment by villesiltala** [comment]
@maavalko, there was an issue in tax calculation for non-taxable order items. This is fixed in [1.1.6](https://github.com/CheckoutFinland/woocommerce-checkout-finland-gateway/releases/tag/1.1.6).
